version: '3.7'

services:
  main:
    container_name: uci-chatbot-helper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    env_file:
      - .env    
    restart: always